sudo: required
services:
  - docker

before_install:
  - docker build -t mstrlarge/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mstrlarge/react-test npm test

after_success:
  - docker build -t mstrlarge/multi-client ./client
  - docker build -t mstrlarge/multi-nginx ./nginx
  - docker build -t mstrlarge/multi-server ./server
  - docker build -t mstrlarge/multi-worker ./worker
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to Docker Hub
  - docker push mstrlarge/multi-client
  - docker push mstrlarge/multi-nginx
  - docker push mstrlarge/multi-server
  - docker push mstrlarge/multi-worker
